// <auto-generated />
using System;
using GenericImporter.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GenericImporter.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211106235846_ImportLayout")]
    partial class ImportLayout
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GenericImporter.Domain.Entities.ImportLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImportLayoutEntity")
                        .HasColumnType("int")
                        .HasColumnName("ImportLayoutEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Separator");

                    b.HasKey("Id");

                    b.ToTable("ImportLayout");
                });

            modelBuilder.Entity("GenericImporter.Domain.Entities.ImportLayoutColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImportLayoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportLayoutId");

                    b.ToTable("ImportLayoutColumn");
                });

            modelBuilder.Entity("GenericImporter.Domain.Entities.Xpto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Xpto");
                });

            modelBuilder.Entity("GenericImporter.Domain.Entities.ImportLayoutColumn", b =>
                {
                    b.HasOne("GenericImporter.Domain.Entities.ImportLayout", "ImportLayout")
                        .WithMany("ImportLayoutColumns")
                        .HasForeignKey("ImportLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportLayout");
                });

            modelBuilder.Entity("GenericImporter.Domain.Entities.ImportLayout", b =>
                {
                    b.Navigation("ImportLayoutColumns");
                });
#pragma warning restore 612, 618
        }
    }
}
